Repository pgadn/qcuicq, pull requests merged in 2022-05, with the labels that each got.

#14 Added disable in checkbox and Created input type option
  src/components/inputs/checkbox/Checkbox.jsx
  src/components/inputs/checkbox/Checkbox.module.scss
  src/components/inputs/index.js
  src/components/inputs/option/Option.jsx
  src/components/inputs/option/Option.module.scss
  src/components/inputs/option/index.js
  src/stories/test/Test.stories.js
  src/styles/global.scss
Labels: enhancement

#18 feature/3-basic-dropdown-input-component
  src/components/inputs/select/InputSelect.module.scss
  src/components/inputs/select/InputSelelct.jsx
  src/components/inputs/select/SelectContext.js
  src/components/inputs/text/InputMask.jsx
  src/components/inputs/text/InputText.jsx
  src/components/inputs/text/InputText.module.scss
  src/stories/signup/Signup.stories.js
  src/styles/global.scss
Labels: feature

#19 release/v1/beta/1.0.17-beta-7
  dist/lib/components/inputs/index.js
  dist/lib/components/inputs/select/InputSelelct.js
  dist/lib/components/inputs/select/SelectContext.js
  dist/lib/components/inputs/text/InputMask.js
  dist/lib/components/inputs/text/InputText.js
  dist/lib/components/inputs/text/index.js
  dist/lib/index.esm.js
  dist/lib/index.js
  dist/lib/styles/index.css
  package.json
  src/components/inputs/select/InputSelect.module.scss
  src/components/inputs/select/InputSelelct.jsx
  src/components/inputs/select/SelectContext.js
  src/components/inputs/text/InputMask.jsx
  src/components/inputs/text/InputText.jsx
  src/components/inputs/text/InputText.module.scss
  src/stories/signup/Signup.stories.js
  src/styles/global.scss
Labels: feature, release (beta)
